version: '2.1'
services:

  webapp-service:
    image: node:8.11.4-slim
    container_name: comunication-webapp
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./webapp:/home/node/app
    command:
#      sh -c 'npm run serve'
      #      sh -c 'npm run lint && npm run serve'
      sh -c 'npm run serve'
    ports:
      - "8080:8080"
    environment:
      - NODE_CONFIG_ENV=development
      - NODE_ENV=development
      - WEBSOCKET_HOST=localhost
      - WEBSOCKET_PORT=8081
      #- NODE_CONFIG_ENV=production
      #- NODE_ENV=production

  api-service:
    container_name: comunication-api
    build: .
    image: culturagovbr/comunication-php-fpm:1.0.1
    working_dir: /application
    volumes:
      - ./api:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
#      - UPDATE_COMPOSER_DEPENDENCIES=true
      - USE_PHP_FPM=true
      - DB_CONNECTION=pgsql
      - DB_HOST=comunication-database
      - DB_PORT=5432
      - DB_DATABASE=notificacao
      - DB_USERNAME=notificacao
      - DB_PASSWORD=senhaNotificacao
    depends_on:
      database-service:
        condition: service_healthy
    links:
      - database-service:comunication-database
    restart: on-failure

  webserver-service:
    image: nginx:alpine
    container_name: comunication-webserver
    working_dir: /application
    volumes:
      - ./api:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "81:80"
    depends_on:
      - api-service

  websocket-service:
    build: ./websocket
    image: comunication-websocket-nodejs:1.0.0
    container_name: comunication-websocket
    ports:
      - "8001:8001"
    depends_on:
      - api-service

  database-service:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notificacao -d notificacao || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    image: postgres:10
    container_name: comunication-database
    environment:
      - POSTGRES_PASSWORD=senhaNotificacao
      - POSTGRES_USER=notificacao
      - POSTGRES_DB=notificacao
      - POSTGRES_DB_TEST=notificacao-test
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - ./database/docker-data/postgres:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/0.schema.sql
      #- ./database/initial-data.sql:/docker-entrypoint-initdb.d/1.data.sql
